<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Admin',
                'email' => 'admin@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kepala Sekolah',
                'email' => 'kepsek@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Kepala Sekolah',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.1',
                'email' => 'walikelas.x.1@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.2',
                'email' => 'walikelas.x.2@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.3',
                'email' => 'walikelas.x.3@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.4',
                'email' => 'walikelas.x.4@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.5',
                'email' => 'walikelas.x.5@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.6',
                'email' => 'walikelas.x.6@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.7',
                'email' => 'walikelas.x.7@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.8',
                'email' => 'walikelas.x.8@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.9',
                'email' => 'walikelas.x.9@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.10',
                'email' => 'walikelas.x.10@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.11',
                'email' => 'walikelas.x.11@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas X.12',
                'email' => 'walikelas.x.12@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Alam.1',
                'email' => 'walikelas.xi.alam.1@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Alam.2',
                'email' => 'walikelas.xi.alam.2@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Alam.3',
                'email' => 'walikelas.xi.alam.3@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Alam.4',
                'email' => 'walikelas.xi.alam.4@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Sosial.1',
                'email' => 'walikelas.xi.sosial.1@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Sosial.2',
                'email' => 'walikelas.xi.sosial.2@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Sosial.3',
                'email' => 'walikelas.xi.sosial.3@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Sosial.4',
                'email' => 'walikelas.xi.sosial.4@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Sosial.5',
                'email' => 'walikelas.xi.sosial.5@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Sosial.6',
                'email' => 'walikelas.xi.sosial.6@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Sosial.7',
                'email' => 'walikelas.xi.sosial.7@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XI.Bahasa.1',
                'email' => 'walikelas.xi.bahasa.1@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Alam.1',
                'email' => 'walikelas.xii.alam.1@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Alam.2',
                'email' => 'walikelas.xii.alam.2@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Alam.3',
                'email' => 'walikelas.xii.alam.3@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Alam.4',
                'email' => 'walikelas.xii.alam.4@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Sosial.1',
                'email' => 'walikelas.xii.sosial.1@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Sosial.2',
                'email' => 'walikelas.xii.sosial.2@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Sosial.3',
                'email' => 'walikelas.xii.sosial.3@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Sosial.4',
                'email' => 'walikelas.xii.sosial.4@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Sosial.5',
                'email' => 'walikelas.xii.sosial.5@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Sosial.6',
                'email' => 'walikelas.xii.sosial.6@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Sosial.7',
                'email' => 'walikelas.xii.sosial.7@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wali Kelas XII.Bahasa.1',
                'email' => 'walikelas.xii.bahasa.1@spk.com',
                'password' => bcrypt('password'),
                'level' => 'Wali Kelas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        \DB::table('users')->insert($users);
    }
}
